[package]
name = "rust_aes256_encrypt_decrypt_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm-siv = "0.10.1"
blake3 = "1.2.0"